[configurationNetwork]
seed = 1
# probability of LoRa device on edge
gamma = 0.5
# probability of device on smartphone
beta = 0.5
dee = 1
dcc = 25
dec = 50
dsc = 150
dlocalhost = 0.015

[brokerHostConfig]
type = "CLOUD"
dataRate = 1e9

[[hostsConfig]]
    type = "CLOUD"
    id = "c000"
[[hostsConfig]]
    type = "EDGE"
    dataRate = 10
