/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
            Versions.com_github_johnrengelman_shadow_gradle_plugin

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" +
            Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.kotlin_scripting_compiler_embeddable

    /**
     * http://www.eclipse.org/paho
     */
    const val org_eclipse_paho_client_mqttv3: String =
            "org.eclipse.paho:org.eclipse.paho.client.mqttv3:" +
            Versions.org_eclipse_paho_client_mqttv3

    /**
     * http://www.github.com/kotlintest/kotlintest
     */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.kotlin_stdlib_jdk8

    /**
     * http://commons.apache.org/proper/commons-logging/
     */
    const val commons_logging: String = "commons-logging:commons-logging:" +
            Versions.commons_logging

    const val moquette_broker: String = "io.moquette:moquette-broker:" + Versions.moquette_broker

    /**
     * https://commons.apache.org/proper/commons-lang/
     */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://commons.apache.org/proper/commons-math/
     */
    const val commons_math3: String = "org.apache.commons:commons-math3:" + Versions.commons_math3

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

    /**
     * https://github.com/msteiger/jxmapviewer2
     */
    const val jxmapviewer2: String = "org.jxmapviewer:jxmapviewer2:" + Versions.jxmapviewer2

    /**
     * http://code.google.com/p/simplelatlng
     */
    const val simplelatlng: String = "com.javadocmd:simplelatlng:" + Versions.simplelatlng

    /**
     * http://commons.apache.org/proper/commons-cli/
     */
    const val commons_cli: String = "commons-cli:commons-cli:" + Versions.commons_cli

    /**
     * https://github.com/classgraph/classgraph
     */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * http://www.jfree.org/jfreechart/
     */
    const val jfreechart: String = "org.jfree:jfreechart:" + Versions.jfreechart

    /**
     * http://flexjson.sourceforge.net/
     */
    const val flexjson: String = "net.sf.flexjson:flexjson:" + Versions.flexjson

    /**
     * http://www.jetbrains.com/
     */
    const val forms_rt: String = "com.intellij:forms_rt:" + Versions.forms_rt

    /**
     * http://www.protelis.org
     */
    const val protelis: String = "org.protelis:protelis:" + Versions.protelis

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/google/guava
     */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/uchuhimo/konf
     */
    const val konf: String = "com.uchuhimo:konf:" + Versions.konf

    /**
     * https://github.com/jenetics/jpx
     */
    const val jpx: String = "io.jenetics:jpx:" + Versions.jpx
}
