import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_github_johnrengelman_shadow_gradle_plugin: String = "5.2.0"

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "8.1.0" // available: "9.2.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.3.61" // available: "1.3.72"

    const val kotlin_scripting_compiler_embeddable: String = "1.3.61" // available: "1.3.72"

    const val kotlintest_runner_junit5: String = "3.3.2" // available: "3.4.2"

    const val kotlin_stdlib_jdk8: String = "1.3.21" // available: "1.3.72"

    const val commons_logging: String = "1.2"

    const val moquette_broker: String = "0.12.1" // available: "0.13"

    const val commons_lang3: String = "3.9" // available: "3.10"

    const val commons_math3: String = "3.6.1"

    const val junit_jupiter: String = "5.5.2" // available: "5.6.2"

    const val jxmapviewer2: String = "2.4" // available: "2.5"

    const val simplelatlng: String = "1.3.1"

    const val commons_cli: String = "1.4"

    const val jfreechart: String = "1.5.0"

    const val flexjson: String = "3.3"

    const val forms_rt: String = "7.0.3"

    const val protelis: String = "13.1.1" // available: "13.3.6"

    const val ktlint: String = "0.33.0" // available: "0.36.0"

    const val guava: String = "28.2-jre"

    const val mockk: String = "1.9.1" // available: "1.10.0"

    const val gson: String = "2.8.5" // available: "2.8.6"

    const val konf: String = "0.13.3" // available: "0.22.1"

    const val jpx: String = "1.4.0" // available: "2.0.0"

    /**
     * Current version: "6.3"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
